"""
dump_foliage_values.py - map-agnostic: extract the ON-DISK density value for EVERY foliage layer+state of the
fruits FoliageMultiLayer, straight from the ENGINE (the packing is engine-internal; no file spells it out).

How: enumerate layers (FML FoliageType children in the map i3d) and states (<foliageState name> in each layer's
foliage XML - $data or mod-local, exactly what GE's dropdowns show). Generate a flag-gated GE headless script
that writes every (layer, state) into a unique test cell via getTerrainDataPlaneByName + DensityMapModifier
(the ENGINE packs the value), saves the combined plane to a SCRATCH gdm (map files untouched), then decode the
cells with our codec -> foliage_values.json {layer: {state: value}}.

Both 1-based and 0-based state-write conventions are probed (two cell bands); the JSON records whichever band
matches known GE-panel anchors (on WW: grass@harvestReady=134, meadow@harvestReady=131).

Usage: python dump_foliage_values.py            (GE must NOT already have the map open)
"""
import os, sys, json, time, subprocess
import xml.etree.ElementTree as ET
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "vendor"))
import gdm_fruits_codec as gf

WW = os.environ.get("FS_CONVERT_HOME") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONV = json.load(open(os.path.join(WW, "tools", os.environ.get("MAP_CONVERT", "wildwest.convert.json")), encoding="utf-8"))
OUT = os.path.join(WW, "out", CONV["identity"]["mod"])
I3D = os.path.join(OUT, "maps", CONV["identity"]["i3d"])
GAME_DATA = r"C:\Program Files (x86)\Steam\steamapps\common\Farming Simulator 25\data"
GE = r"C:\Program Files\GIANTS Software\GIANTS_Editor_10.0.13\editor.exe"
GE_SCRIPTS = r"C:\Program Files\GIANTS Software\GIANTS_Editor_10.0.13\scripts"
SCR = r"C:\Temp\claude\C--repos-fs25-orchestrator\33afca5d-177b-46f7-908f-bd6466f541dd\scratchpad\foliage_dump"
JSON_OUT = os.path.join(WW, "tools", "foliage_values.json")

CELL = 8.0    # test cell size (m)
STEP = 24.0   # cell stride (m)
BASE = -3900.0  # SW corner area; safe inside any 8192 map


def resolve(path, i3d_dir):
    if path.startswith("$data/"):
        return os.path.join(GAME_DATA, path[6:].replace("/", os.sep))
    return os.path.normpath(os.path.join(i3d_dir, path.replace("/", os.sep)))


def enumerate_layers():
    root = ET.parse(I3D).getroot()
    files = {f.get("fileId"): f.get("filename") for f in root.iter("File")}
    i3d_dir = os.path.dirname(I3D)
    for fml in root.iter("FoliageMultiLayer"):
        names = [t.get("name") for t in fml.findall("FoliageType")]
        if "grass" not in names:
            continue
        layers = []
        for t in fml.findall("FoliageType"):
            xml_path = resolve(files.get(t.get("foliageXmlId"), ""), i3d_dir)
            states = []
            try:
                froot = ET.parse(xml_path).getroot()
                for st in froot.iter("foliageState"):
                    states.append(st.get("name") or f"state{len(states)}")
            except Exception as e:
                print(f"  WARN: {t.get('name')}: cannot parse {xml_path}: {e}")
            layers.append({"name": t.get("name"), "states": states})
        return layers
    raise SystemExit("no fruits FoliageMultiLayer (grass) found in i3d")


LUA = """-- Name: zzFoliageValueDump (GENERATED by dump_foliage_values.py - do not edit)
-- Hide: yes
-- AlwaysLoaded: yes
local SCR  = "{scr}/"
local FLAG = "{scr}/dump.flag"
local LAYERS = {{{layers_lua}}}
local function cellWrite(mod, x, z, v)
    mod:setParallelogramWorldCoords(x, z, x + {cell}, z, x, z + {cell}, DensityCoordType.POINT_POINT_POINT)
    mod:executeSet(v)
end
local function run(filepath)
    if not fileExists(FLAG) then return end
    print("==== FOLIAGE VALUE DUMP: start ====")
    createFolder(SCR)
    local terrain = getChild(getRootNode(), "terrain")
    local anyHandle = nil
    for li, L in ipairs(LAYERS) do
        local h = getTerrainDataPlaneByName(terrain, L.name)
        if h ~= nil and h ~= 0 then
            anyHandle = anyHandle or h
            local mod = DensityMapModifier.new(h, 0, 4, terrain)
            for si = 1, L.n do
                local x = {base} + (li - 1) * {step}
                cellWrite(mod, x, {base} + (si - 1) * {step}, si)          -- band A: 1-based write
                cellWrite(mod, x, {base} + 2400 + (si - 1) * {step}, si - 1) -- band B: 0-based write
            end
        else
            createFolder(SCR .. "NOHANDLE_" .. L.name)
        end
    end
    if anyHandle then
        local ok = pcall(function() saveDensityMapToFile(anyHandle, SCR .. "fruits_dump.gdm") end)
        createFolder(SCR .. (ok and "save_OK" or "save_FAIL"))
    end
    createFolder(SCR .. "done")
    print("==== FOLIAGE VALUE DUMP: done ====")
end
addEventListener(HookType.ON_FILE_OPEN, run)
"""


def main():
    layers = enumerate_layers()
    print(f"fruits FML: {len(layers)} layers; states: " +
          ", ".join(f"{L['name']}({len(L['states'])})" for L in layers))

    os.makedirs(SCR, exist_ok=True)
    scr_fwd = SCR.replace("\\", "/")
    layers_lua = ", ".join('{name="%s", n=%d}' % (L["name"], len(L["states"])) for L in layers)
    lua = LUA.format(scr=scr_fwd, layers_lua=layers_lua, cell=CELL, step=STEP, base=BASE)
    open(os.path.join(GE_SCRIPTS, "zz_foliage_value_dump.lua"), "w", encoding="utf-8").write(lua)
    open(os.path.join(SCR, "dump.flag"), "w").write("1")
    done = os.path.join(SCR, "done")
    if os.path.exists(done):
        os.rmdir(done)

    print("launching GE headless...")
    ge = subprocess.Popen([GE, I3D])
    t0 = time.time()
    while not os.path.exists(done):
        if time.time() - t0 > 900:
            ge.kill(); raise SystemExit("GE dump timed out")
        time.sleep(5)
    time.sleep(3)
    ge.kill()
    os.remove(os.path.join(SCR, "dump.flag"))

    # decode the scratch gdm at the test cells
    src = os.path.join(SCR, "fruits_dump.gdm")
    vals = gf.decode_full(src)
    N = vals.shape[0]; half = N / 2  # px; 2 px per metre on 16k/8192 maps
    ppm = N / 8192.0

    def read_cell(x, z):
        px = int((x + 4096) * ppm + CELL * ppm / 2)
        pz = int((z + 4096) * ppm + CELL * ppm / 2)
        return int(vals[pz, px])

    table = {}
    for li, L in enumerate(layers):
        x = BASE + li * STEP
        entry = {}
        for si, sname in enumerate(L["states"], start=1):
            v1 = read_cell(x, BASE + (si - 1) * STEP)
            v0 = read_cell(x, BASE + 2400 + (si - 1) * STEP)
            entry[sname] = {"write1": v1, "write0": v0}
        table[L["name"]] = entry
    json.dump(table, open(JSON_OUT, "w"), indent=1)
    print(f"wrote {JSON_OUT}")

    # anchor check (WW): GE panel says grass@harvestReady=134, meadow@harvestReady=131
    g = table.get("grass", {}).get("harvestReady", {})
    m = table.get("meadow", {}).get("harvestReady", {})
    print(f"anchor grass@harvestReady:  write1={g.get('write1')} write0={g.get('write0')} (GE panel: 134)")
    print(f"anchor meadow@harvestReady: write1={m.get('write1')} write0={m.get('write0')} (GE panel: 131)")


if __name__ == "__main__":
    main()
